
var TABLE_INFO = [
	{
		id: "smbg",
		alias: "Self-monitored Blood Glucose",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Value', id: 'value', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Subtype', id: 'subType', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "cbg",
		alias: "Continuous Blood Glucose",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Value', id: 'value', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "bolus",
		alias: "Bolus Insulin",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Subtype', id: 'subType', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Normal', id: 'normal', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Expected Normal', id: 'expectedNormal', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Extended', id: 'extended', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Expected Extended', id: 'expectedExtended', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Duration', id: 'duration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Expected Duration', id: 'expectedDuration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "bloodKetone",
		alias: "Blood Ketone Levels",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Value', id: 'value', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "cgmSettings",
		alias: "Continuous Glucose Monitor Settings",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'High Alerts Enabled', id: 'highAlerts', dataType: tableau.dataTypeEnum.string},
			{ alias: 'High Alerts Level', id: 'highAlertsLevel', dataType: tableau.dataTypeEnum.string},
			{ alias: 'High Alerts Snooze', id: 'highAlertsSnooze', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Low Alerts Enabled', id: 'lowAlerts', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Low Alerts Level', id: 'lowAlertsLevel', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Low Alerts Snooze', id: 'lowAlertsSnooze', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Out of Range Alerts Enabled', id: 'outOfRangeAlerts', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Out of Range Alerts Snooze', id: 'outOfRangeAlertsSnooze', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Fall Rate Alerts Enabled', id: 'fallRateAlerts', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Fall Rate Alerts Rate', id: 'fallRateAlertsRate', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Rise Rate Alerts Enabled', id: 'riseRateAlerts', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Rise Rate Alerts Rate', id: 'riseRateAlertsRate', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Transmitter Id', id: 'transmitterId', dataType: tableau.dataTypeEnum.string},
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "basalSchedule",
		alias: "Basal Schedule",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Sequence', id: 'sequence', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Active Schedule', id: 'activeSchedule', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Schedule Name', id: 'scheduleName', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Rate', id: 'rate', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Start', id: 'start', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "bgTarget",
		alias: "Blood Glucose Target",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Sequence', id: 'sequence', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Low', id: 'low', dataType: tableau.dataTypeEnum.string },
			{ alias: 'High', id: 'high', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Start', id: 'start', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "carbRatio",
		alias: "Carb Ratio",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Sequence', id: 'sequence', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Amount', id: 'amount', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Start', id: 'start', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "insulinSensitivity",
		alias: "Insulin Sensitivity",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Sequence', id: 'sequence', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Amount', id: 'amount', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Start', id: 'start', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "wizard",
		alias: "(Bolus) Calculator/\"Wizard\" records",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'BG Input', id: 'bgInput', dataType: tableau.dataTypeEnum.string },
			{ alias: 'BG Target', id: 'bgTarget', dataType: tableau.dataTypeEnum.string },
			{ alias: 'BG Target Low', id: 'bgTargetLow', dataType: tableau.dataTypeEnum.string },
			{ alias: 'BG Target High', id: 'bgTargetHigh', dataType: tableau.dataTypeEnum.string },
			{ alias: 'BG Target Range', id: 'bgTargetRange', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Bolus Id', id: 'bolus', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Carb Input', id: 'carbInput', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Insulin Carb Ratio', id: 'insulinCarbRatio', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Insulin On Board', id: 'insulinOnBoard', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Insulin Sensitivity', id: 'insulinSensitivity', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Recommended Units for Carbs', id: 'recommendedCarb', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Recommended Units for Correction', id: 'recommendedCorrection', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Recommended Net Units', id: 'recommendedNet', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "upload",
		alias: "Upload Metadata",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Uploaded by User', id: 'byUser', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Uploaded by User', id: 'hash_byUser', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Manufacturer', id: 'deviceManufacturer', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Model', id: 'deviceModel', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Serial Number', id: 'deviceSerialNumber', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Tag', id: 'deviceTag', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Computer Time', id: 'computerTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Time Processing', id: 'timeProcessing', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Version', id: 'version', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "deviceEvent",
		alias: "Miscellaneous other device events",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Subtype', id: 'subType', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Alarm Type', id: 'alarmType', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Value', id: 'value', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Prime Target', id: 'primeTarget', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Volume', id: 'volume', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Time Change From', id: 'timeChangeFrom', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time Change To', id: 'timeChangeTo', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time Change Agent', id: 'timeChangeAgent', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time Change Reasons', id: 'timeChangeReasons', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time Change Timezone', id: 'timeChangeTimezone', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Status', id: 'status', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Duration', id: 'duration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Expected Duration', id: 'expectedDuration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Reason Suspended', id: 'reasonSuspended', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Reason Resumed', id: 'reasonResumed', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	},{
		id: "basal",
		alias: "Basal Insulin",
		columns: [
			{ alias: 'Index', id: 'index', dataType: tableau.dataTypeEnum.int },
			{ alias: 'Group', id: 'group', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Suppressed', id: 'suppressed', dataType: tableau.dataTypeEnum.bool },
			{ alias: 'Delivery Type', id: 'deliveryType', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Duration', id: 'duration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Expected Duration', id: 'expectedDuration', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Percent', id: 'percent', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Rate', id: 'rate', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Units', id: 'units', dataType: tableau.dataTypeEnum.float },
			{ alias: 'Schedule Name', id: 'scheduleName', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Source', id: 'source', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Id', id: 'deviceId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Device Time', id: 'deviceTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Time', id: 'time', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Timezone Offset', id: 'timezoneOffset', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Clock Drift Offset', id: 'clockDriftOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Conversion Offset', id: 'conversionOffset', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Id', id: 'id', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Created Time', id: 'createdTime', dataType: tableau.dataTypeEnum.datetime },
			{ alias: 'Hash Upload Id', id: 'hash_uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Hash Group Id', id: 'hash_groupId', dataType: tableau.dataTypeEnum.string },
			{ alias: 'Payload', id: 'payload', dataType: tableau.dataTypeEnum.string },
			{ alias: 'GUID', id: 'guid', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: 'uploadId', dataType: tableau.dataTypeEnum.string },
			{ alias: null, id: '_groupId', dataType: tableau.dataTypeEnum.string }
		]
	}
];
